# Generated by Django 3.1.7 on 2021-06-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=40)),
                ('dname', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=40)),
                ('dyear', models.DateField()),
                ('hsc', models.CharField(max_length=50)),
                ('score', models.FloatField()),
                ('hyear', models.DateField()),
                ('ssc', models.CharField(max_length=50)),
                ('sscore', models.FloatField()),
                ('syear', models.DateField()),
                ('experience', models.CharField(max_length=500)),
                ('skills', models.CharField(max_length=500)),
                ('awards', models.CharField(max_length=500)),
            ],
        ),
    ]
