# Generated by Django 3.1.7 on 2021-07-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelaccept',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
