# Generated by Django 3.1.7 on 2021-06-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='score',
        ),
        migrations.AddField(
            model_name='details',
            name='dscore',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='hscore',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='styear',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='dyear',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='details',
            name='hyear',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='details',
            name='sscore',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='details',
            name='syear',
            field=models.CharField(max_length=20),
        ),
    ]
