# Generated by Django 3.1.7 on 2021-06-27 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210627_1935'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='details',
            table=None,
        ),
    ]
