# Generated by Django 3.1.7 on 2021-07-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210711_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelaccept',
            name='fullname',
        ),
        migrations.AddField(
            model_name='modelaccept',
            name='awards',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='modelaccept',
            name='branch',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='modelaccept',
            name='dname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='modelaccept',
            name='dscore',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='modelaccept',
            name='dyear',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='modelaccept',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='modelaccept',
            name='experience',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='modelaccept',
            name='fname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='modelaccept',
            name='hsc',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='modelaccept',
            name='hscore',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='modelaccept',
            name='hyear',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='modelaccept',
            name='lname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='modelaccept',
            name='number',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='modelaccept',
            name='skills',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='modelaccept',
            name='ssc',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='modelaccept',
            name='sscore',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='modelaccept',
            name='styear',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='modelaccept',
            name='syear',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
