# Generated by Django 3.1.7 on 2021-06-27 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210627_1945'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='details',
            table='details',
        ),
    ]
