# Generated by Django 3.1.7 on 2021-07-02 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210627_1948'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='details',
            table='Detailss',
        ),
    ]
