# Generated by Django 3.1.7 on 2021-07-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210712_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelaccept',
            name='link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
