# Generated by Django 3.1.7 on 2021-07-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_modelaccept_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelaccept',
            name='specification',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
