# Generated by Django 3.1.7 on 2021-07-02 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210702_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='awards',
            new_name='Awards',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='branch',
            new_name='Branch',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='dname',
            new_name='Dname',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='dscore',
            new_name='Dscore',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='dyear',
            new_name='Dyear',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='experience',
            new_name='Experience',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='fname',
            new_name='Fname',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='hsc',
            new_name='Hsc',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='hscore',
            new_name='Hscore',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='hyear',
            new_name='Hyear',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='lname',
            new_name='Lname',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='number',
            new_name='Number',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='skills',
            new_name='Skills',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='ssc',
            new_name='Ssc',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='sscore',
            new_name='Sscore',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='styear',
            new_name='Styear',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='syear',
            new_name='Syear',
        ),
    ]
