# Generated by Django 3.1.7 on 2021-07-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210702_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='Email',
            field=models.CharField(max_length=100),
        ),
    ]
